language: python
dist: xenial

before_install:
  - sudo apt-get install -y python-virtualenv
  - virtualenv planemo-venv
  - . planemo-venv/bin/activate
  - pip install planemo==0.58.1
  - planemo conda_init

install:
  - planemo conda_install ${TRAVIS_BUILD_DIR}
  - sudo apt-get install r-base libxml2-dev libcurl4-openssl-dev libssl-dev liblapack-dev
  - sudo chmod 777 -R /usr/local/lib/R/site-library
  - Rscript -e 'install.packages(c("parallel", "pbapply", "grDevices", "ggplot2", "optparse", "scales", "igraph", "gridExtra", "Deriv", "openxlsx", "devtools", "rmarkdown", "pander", "ggrepel", "plotly", "visNetwork"), repos = "http://cran.us.r-project.org")' && \
  - R -e 'devtools::install_github("rgcca-factory/RGCCA", ref = "3.0.0")'
  - git clone --depth 1 --single-branch --branch https://github.com/rgcca-factory/RGCCA.git
  - cd ${TRAVIS_BUILD_DIR}/RGCCA
  - git checkout 3.0.0
  - cd ${TRAVIS_BUILD_DIR}
  # - cp -r ${TRAVIS_BUILD_DIR}/RGCCA/R ${TRAVIS_BUILD_DIR}/R
  - mv ${TRAVIS_BUILD_DIR}/RGCCA/inst/launcher.R ${TRAVIS_BUILD_DIR}/launcher.R

script:
  - planemo lint ${TRAVIS_BUILD_DIR}
  - planemo test --conda_debug --no_cache_galaxy --galaxy_branch release_18.05 --file_path ${TRAVIS_BUILD_DIR} --job_output_files ${TRAVIS_BUILD_DIR} ${TRAVIS_BUILD_DIR}

after_script:
  - ls ${TRAVIS_BUILD_DIR}
  - cat tool_test_output.json