language: python
dist: xenial

before_install:
  - sudo apt-get install -y python-virtualenv r-base libxml2-dev libcurl4-openssl-dev libssl-dev liblapack-dev
  - sudo R -e 'install.packages(c("RGCCA","ggplot2","optparse","scales","igraph"),  repos = "http://cran.us.r-project.org")'
  - virtualenv planemo-venv
  - . planemo-venv/bin/activate
  - pip install --upgrade pip setuptools
  - pip install planemo==0.47.0

script:
  - planemo lint ${TRAVIS_BUILD_DIR}
  - planemo test --conda_auto_init --conda_auto_install --conda_dependency_resolution --conda_debug --no_cache_galaxy --file_path ${TRAVIS_BUILD_DIR} --job_output_files ${TRAVIS_BUILD_DIR} ${TRAVIS_BUILD_DIR}

after_script:
  - ls ${TRAVIS_BUILD_DIR}
  - cat tool_test_output.json
  - head ${TRAVIS_BUILD_DIR}/individuals.tsv ${TRAVIS_BUILD_DIR}/variables.tsv
  - wc ${TRAVIS_BUILD_DIR}/individuals.tsv ${TRAVIS_BUILD_DIR}/variables.tsv