language: python

env:
  global:
    - TOOL_VERSION=3.0.0
    - TOOL_NAME=RGCCA

before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -n test -c icm-iconics -c bioconda -c conda-forge r-rgcca

install:
  - conda activate test
  - conda install planemo libgfortran r-base r-gridextra r-deriv r-mass r-ggplot2 r-optparse r-scales r-igraph r-pbapply r-plotly git
  - git clone --depth 1 --single-branch --branch $TOOL_VERSION https://github.com/rgcca-factory/$TOOL_NAME
  - cd ${CONDA_PREFIX}/${TOOL_NAME}
  - git checkout ${TOOL_VERSION}
  - cd ${CONDA_PREFIX}
  - R CMD build --no-build-vignettes ${TOOL_NAME}
  - R -e "install.packages('"${TOOL_NAME}_${TOOL_VERSION}".tar.gz'"", repos = NULL, type = 'source')"
  # - cp -r ${TRAVIS_BUILD_DIR}/RGCCA/R ${TRAVIS_BUILD_DIR}/R
  - mv ${CONDA_PREFIX}/${TOOL_NAME}/inst/launcher.R ${CONDA_PREFIX}/launcher.R

script:
  - planemo lint ${CONDA_PREFIX}
  - planemo test --conda_debug --no_cache_galaxy --galaxy_branch release_18.05 --file_path ${CONDA_PREFIX} --job_output_files ${CONDA_PREFIX} ${CONDA_PREFIX}

after_script:
  - ls ${CONDA_PREFIX}
  - cat tool_test_output.json