language: python
dist: xenial

env:
  global:
    - TOOL_VERSION=3.0.0
    - TOOL_NAME=RGCCA
    - PKGS='libxml2-dev libcurl4-openssl-dev libssl-dev liblapack-dev r-base'
    - RPKGS='parallel pbapply grDevices ggplot2 optparse scales igraph gridExtra Deriv openxlsx devtools rmarkdown pander ggrepel plotly visNetwork'

before_install:
  - sudo apt-get install -y python-virtualenv
  - virtualenv planemo-venv
  - . planemo-venv/bin/activate
  - pip install planemo==0.58.1
  - planemo conda_init

install:
  - planemo conda_install ${TRAVIS_BUILD_DIR}
  - sudo apt-get install -y ${PKGS}
  - sudo chmod 777 -R /usr/local/lib/R/site-library
  - Rscript -e 'install.packages(commandArgs(TRUE),repos = "http://cran.us.r-project.org")' ${RPKGS}
  - R -e 'devtools::install_github("rgcca-factory/'${TOOL_NAME}'", ref = "'${TOOL_VERSION}'")'
  - git clone --depth 1 --single-branch --branch https://github.com/rgcca-factory/RGCCA.git
  - cd ${TRAVIS_BUILD_DIR}/${TOOL_NAME}
  - git checkout ${TOOL_VERSION}
  - cd ${TRAVIS_BUILD_DIR}
  # - cp -r ${TRAVIS_BUILD_DIR}/RGCCA/R ${TRAVIS_BUILD_DIR}/R
  - mv ${TRAVIS_BUILD_DIR}/${TOOL_NAME}/inst/launcher.R ${TRAVIS_BUILD_DIR}/launcher.R

script:
  - planemo lint ${TRAVIS_BUILD_DIR}
  - planemo test --conda_debug --no_cache_galaxy --galaxy_branch release_18.05 --file_path ${TRAVIS_BUILD_DIR} --job_output_files ${TRAVIS_BUILD_DIR} ${TRAVIS_BUILD_DIR}

after_script:
  - ls ${TRAVIS_BUILD_DIR}
  - cat tool_test_output.json